### PR TITLE
Add select2.full.js to resolve Error: No select2/compat/inputData

### PR DESCRIPTION
**Pull request by rolme**
When using select2 with x-editable, the full version (select2.full.js) is required. I have added it to the rails gem.

Related info:
https://groups.google.com/forum/#!topic/select2/yifYbU1HPOY
https://github.com/select2/select2/issues/3057

### CODE REVIEW

**Comment by george1minus1** [comment]
This would be awesome to get merged in as having the same issue.

**Comment by sgranata82** [comment]
+1

**Comment by tlluiz** [comment]
:+1:

**Comment by bitsapien** [comment]
Why is this still pending ?

**Comment by TSMMark** [comment]
+1 please merge

**Comment by bmkiefer** [comment]
+ 1

**Comment by sder3dgh** [comment]
+1 please merge

**Comment by simi** [comment]
Hello! Can you please update also https://github.com/argerim/select2-rails/blob/b9916373327871a9478775fca53296b2be406af6/lib/select2-rails/source_file.rb and README.md?

**Comment by steveyken** [comment]
Thanks for this fix. Any chance of a new gem release?

**Comment by simi** [comment]
only @argerim can release right now

**Pull request merged**
