### PR TITLE
Finalize v4 update

### PR DESCRIPTION
**Pull request by nilbus**
This branch is based on #114 frodrigo:v4, with two fixes:
1. Fix rake update-select2 to work with the new v4 files and locales
2. Update locale assets via rake update-select2

I have tested this branch in a real app, and it works great.
Things are simpler now that v4 has no images.

@frodrigo set the version number to 4.0.0, but feel free to change to 4.0.0.0 if you
think that will be more consistent.

### CODE REVIEW

**Comment by nilbus** [comment]
@simi @argerim Will it be possible for you to test and release this today or this week? If anything needs to be done to make this happen, I will be glad to assist.

**Comment by nilbus** [comment]
@simi I saw you self-assigned this. Any feedback?

**Comment by simi** [comment]
Sure. But I need to finish review first. This is huge change.

**Comment by nilbus** [comment]
Thanks :)

**Comment by nilbus** [comment]
@simi How's it looking? Any progress this week?

**Comment by gomayonqui** [comment]
Any plans to merge this soon? :smiley:

**Comment by gomayonqui** [comment]
I'm using @nilbus fork and it works pretty good. Any reason this haven't been merge yet?

**Comment by nilbus** [comment]
@simi One less-arduous way you might approach this review is to:

1. Inspect the updated rake task to verify you think it does the right thing.
2. Run the rake task, and verify that it updates the files in the same way that were committed.

**Comment by erkaun** [comment]
I don't have any suggestions for what is a ton of review work, but just wanted to mention that I've had great results with this so far, and would like this released even more than I'd like a large block of cheese. And I love cheese.

**Comment by nilbus** [comment]
While we wait for the official release, I have released the nilbus:v4 branch as 4.0.0 to an unofficial gem server. You can add this to your Gemfile to use it:

```ruby
gem "select2-rails", "~> 4.0", source: "http://osm-gems.s3-website-us-west-2.amazonaws.com"
```

**Comment by simi** [comment]
It is merged into master. Thanks for your patience and work! I try to release ASAP, but I have not permission for that. Stay tuned.

**Comment by nilbus** [comment]
@simi Thank you for the review!

**Comment by erkaun** [comment]
@argerim, do you have an estimate on when this update to master will be released?

**Comment by simi** [comment]
@erkaun it is out.

**Comment by nilbus** [comment]
Thanks @simi for working to make this happen! :checkered_flag:

**Comment by erkaun** [comment]
Thanks @simi and @nilbus! This is very much appreciated.

**Pull request closed without merging**
