### PR TITLE
Updated assets with the latest version of select2 (4.0.0)

### PR DESCRIPTION
**Pull request by josetapadas**

### CODE REVIEW

**Comment by josetapadas** [comment]
Olá @argerim , será que podes testar e perceber se podemos fazer o merge deste branch?

Obrigado, abraço!

**Comment by kevin-brown** [comment]
Looks to be a duplicate of https://github.com/argerim/select2-rails/pull/114.

**Comment by josetapadas** [comment]
Yes it does.

**Comment by plentz** [comment]
already fixed

**Comment by simi** [comment]
yes, thanks for notice

**Pull request closed without merging**
