### PR TITLE
Include select2.full.js

### PR DESCRIPTION
**Pull request by nilbus**
This attempts to address #131 for @PlugIN73

This should work, in theory, but I haven't had time to test it.

### CODE REVIEW

**Comment by nilbus** [comment]
@PlugIN73 Could you point your Gemfile to this branch to test if this works for you?

```ruby
gem "select2-rails", ">= 4.0.0.1", github: 'nilbus/select2-rails', branch: 'full'
```

**Comment by nilbus** [comment]
I confirmed in my app that this works as intended.

    #= require select2.full

**Comment by PlugIN73** [comment]
Oh, sorry - i didn't receive notification for first comment :( I will try today later, thank you!

**Comment by PlugIN73** [comment]
@nilbus yes, it works :) Can you merge it?

**Comment by simi** [comment]
Can you add README.md note?

**Comment by nilbus** [comment]
I'll add that later today.

**Comment by nilbus** [comment]
@simi How does that look?

**Comment by nilbus** [comment]
I just amended the last commit to fix a typo in the URI scheme for the select2 builds link.

**Comment by ryanharkins** [comment]
:+1:

**Comment by bingxie** [comment]
And if you want to use matcher you also need to use select2.full. Wish this one will be merged soon.

**Comment by sgranata82** [comment]
+1

**Comment by maokomioko** [comment]
Any news? :)

**Comment by jtapia** [comment]
this allow you to use `dropdownCssClass`? I used your repo and it still being an issue `No select2/compat/dropdownCss`

**Comment by kovalevsky** [comment]
Any news?
lgtm!

**Comment by simi** [comment]
damn, I forgot to close this one

full version is already part of gem - see https://github.com/argerim/select2-rails#include-select2-rails-javascript-assets for more info

**Pull request closed without merging**
