### PR TITLE
Add assets paths (fix #164).

### LINKED ISSUE #164: Sprockets::FileNotFound at / - couldn't find file 'select2' with type 'text/scss'
Ruby: 2.3.1p112
Rails: 5.0.0
Bundler: 1.12.5

After updating to above mentioned environment, app is throwing following exception.

`Sprockets::FileNotFound - couldn't find file 'select2' with type 'text/scss':
` 

Full Stack trace:
`Sprockets::FileNotFound - couldn't find file 'select2' with type 'text/scss':
  sprockets (4.0.0.beta2) lib/sprockets/directive_processor.rb:178:in`rescue in block in process_directives'
  sprockets (4.0.0.beta2) lib/sprockets/directive_processor.rb:175:in `block in process_directives'
  sprockets (4.0.0.beta2) lib/sprockets/directive_processor.rb:174:in`process_directives'
  sprockets (4.0.0.beta2) lib/sprockets/directive_processor.rb:79:in `_call'
  sprockets (4.0.0.beta2) lib/sprockets/directive_processor.rb:64:in`call'
  sprockets (4.0.0.beta2) lib/sprockets/processor_utils.rb:83:in `call_processor'
  sprockets (4.0.0.beta2) lib/sprockets/processor_utils.rb:65:in`block in call_processors'
  sprockets (4.0.0.beta2) lib/sprockets/processor_utils.rb:64:in `call_processors'
  sprockets (4.0.0.beta2) lib/sprockets/loader.rb:147:in`load_from_unloaded'
  sprockets (4.0.0.beta2) lib/sprockets/loader.rb:58:in `block in load'
  sprockets (4.0.0.beta2) lib/sprockets/loader.rb:323:in`fetch_asset_from_dependency_cache'
  sprockets (4.0.0.beta2) lib/sprockets/loader.rb:42:in `load'
  sprockets (4.0.0.beta2) lib/sprockets/cached_environment.rb:20:in`block in initialize'
  sprockets (4.0.0.beta2) lib/sprockets/cached_environment.rb:47:in `load'
  sprockets (4.0.0.beta2) lib/sprockets/source_map_processor.rb:32:in`block in call'
  sprockets (4.0.0.beta2) lib/sprockets/source_map_processor.rb:23:in `call'
  sprockets (4.0.0.beta2) lib/sprockets/processor_utils.rb:83:in`call_processor'
  sprockets (4.0.0.beta2) lib/sprockets/processor_utils.rb:65:in `block in call_processors'
  sprockets (4.0.0.beta2) lib/sprockets/processor_utils.rb:64:in`call_processors'
  sprockets (4.0.0.beta2) lib/sprockets/loader.rb:147:in `load_from_unloaded'
  sprockets (4.0.0.beta2) lib/sprockets/loader.rb:58:in`block in load'
  sprockets (4.0.0.beta2) lib/sprockets/loader.rb:323:in `fetch_asset_from_dependency_cache'
  sprockets (4.0.0.beta2) lib/sprockets/loader.rb:42:in`load'
  sprockets (4.0.0.beta2) lib/sprockets/cached_environment.rb:20:in `block in initialize'
  sprockets (4.0.0.beta2) lib/sprockets/cached_environment.rb:47:in`load'
  sprockets (4.0.0.beta2) lib/sprockets/source_map_comment_processor.rb:21:in `call'
  sprockets (4.0.0.beta2) lib/sprockets/processor_utils.rb:83:in`call_processor'
  sprockets (4.0.0.beta2) lib/sprockets/processor_utils.rb:65:in `block in call_processors'
  sprockets (4.0.0.beta2) lib/sprockets/processor_utils.rb:64:in`call_processors'
  sprockets (4.0.0.beta2) lib/sprockets/loader.rb:147:in `load_from_unloaded'
  sprockets (4.0.0.beta2) lib/sprockets/loader.rb:58:in`block in load'
  sprockets (4.0.0.beta2) lib/sprockets/loader.rb:323:in `fetch_asset_from_dependency_cache'
  sprockets (4.0.0.beta2) lib/sprockets/loader.rb:42:in`load'
  sprockets (4.0.0.beta2) lib/sprockets/cached_environment.rb:20:in `block in initialize'
  sprockets (4.0.0.beta2) lib/sprockets/cached_environment.rb:47:in`load'
  sprockets (4.0.0.beta2) lib/sprockets/base.rb:66:in `find_asset'
  sprockets (4.0.0.beta2) lib/sprockets/base.rb:92:in`[]'
  sprockets-rails (3.1.1) lib/sprockets/rails/helper.rb:338:in `find_asset'
  sprockets-rails (3.1.1) lib/sprockets/rails/helper.rb:330:in`find_debug_asset'
  sprockets-rails (3.1.1) lib/sprockets/rails/helper.rb:212:in `block in lookup_debug_asset'
  sprockets-rails (3.1.1) lib/sprockets/rails/helper.rb:225:in`block in resolve_asset'
  sprockets-rails (3.1.1) lib/sprockets/rails/helper.rb:224:in `resolve_asset'
  sprockets-rails (3.1.1) lib/sprockets/rails/helper.rb:211:in`lookup_debug_asset'
  sprockets-rails (3.1.1) lib/sprockets/rails/helper.rb:153:in `block in stylesheet_link_tag'
  sprockets-rails (3.1.1) lib/sprockets/rails/helper.rb:152:in`stylesheet_link_tag'
  app/views/site/home.html.erb:2:in `block in _app_views_site_home_html_erb___4049320098311539870_70249673506360'
  actionview (5.0.0) lib/action_view/helpers/capture_helper.rb:39:in`block in capture'
  actionview (5.0.0) lib/action_view/helpers/capture_helper.rb:203:in `with_output_buffer'
  actionview (5.0.0) lib/action_view/helpers/capture_helper.rb:39:in`capture'
  actionview (5.0.0) lib/action_view/helpers/capture_helper.rb:153:in `content_for'
  app/views/site/home.html.erb:1:in`_app_views_site_home_html_erb___4049320098311539870_70249673506360'
  actionview (5.0.0) lib/action_view/template.rb:158:in `block in render'
  activesupport (5.0.0) lib/active_support/notifications.rb:166:in`instrument'
  actionview (5.0.0) lib/action_view/template.rb:348:in `instrument'
  actionview (5.0.0) lib/action_view/template.rb:156:in`render'
  actionview (5.0.0) lib/action_view/renderer/template_renderer.rb:54:in `block (2 levels) in render_template'
  actionview (5.0.0) lib/action_view/renderer/abstract_renderer.rb:42:in`block in instrument'
  activesupport (5.0.0) lib/active_support/notifications.rb:164:in `block in instrument'
  activesupport (5.0.0) lib/active_support/notifications/instrumenter.rb:21:in`instrument'
  activesupport (5.0.0) lib/active_support/notifications.rb:164:in `instrument'
  actionview (5.0.0) lib/action_view/renderer/abstract_renderer.rb:41:in`instrument'
  actionview (5.0.0) lib/action_view/renderer/template_renderer.rb:53:in `block in render_template'
  actionview (5.0.0) lib/action_view/renderer/template_renderer.rb:61:in`render_with_layout'
  actionview (5.0.0) lib/action_view/renderer/template_renderer.rb:52:in `render_template'
  actionview (5.0.0) lib/action_view/renderer/template_renderer.rb:14:in`render'
  actionview (5.0.0) lib/action_view/renderer/renderer.rb:42:in `render_template'
  actionview (5.0.0) lib/action_view/renderer/renderer.rb:23:in`render'
  actionview (5.0.0) lib/action_view/rendering.rb:103:in `_render_template'
  actionpack (5.0.0) lib/action_controller/metal/streaming.rb:217:in`_render_template'
  actionview (5.0.0) lib/action_view/rendering.rb:83:in `render_to_body'
  actionpack (5.0.0) lib/action_controller/metal/rendering.rb:52:in`render_to_body'
  actionpack (5.0.0) lib/action_controller/metal/renderers.rb:144:in `render_to_body'
  actionpack (5.0.0) lib/abstract_controller/rendering.rb:26:in`render'
  actionpack (5.0.0) lib/action_controller/metal/rendering.rb:36:in `render'
  actionpack (5.0.0) lib/action_controller/metal/instrumentation.rb:44:in`block (2 levels) in render'
  activesupport (5.0.0) lib/active_support/core_ext/benchmark.rb:12:in `block in ms'
  /Users/umesh/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/benchmark.rb:308:in`realtime'
  activesupport (5.0.0) lib/active_support/core_ext/benchmark.rb:12:in `ms'
  actionpack (5.0.0) lib/action_controller/metal/instrumentation.rb:44:in`block in render'
  actionpack (5.0.0) lib/action_controller/metal/instrumentation.rb:87:in `cleanup_view_runtime'
  activerecord (5.0.0) lib/active_record/railties/controller_runtime.rb:25:in`cleanup_view_runtime'
  actionpack (5.0.0) lib/action_controller/metal/instrumentation.rb:43:in `render'
  wicked_pdf (1.0.6) lib/wicked_pdf/pdf_helper.rb:22:in`render_with_wicked_pdf'
  actionpack (5.0.0) lib/action_controller/metal/implicit_render.rb:36:in `default_render'
  actionpack (5.0.0) lib/action_controller/metal/basic_implicit_render.rb:4:in`block in send_action'
  actionpack (5.0.0) lib/action_controller/metal/basic_implicit_render.rb:4:in `send_action'
  actionpack (5.0.0) lib/abstract_controller/base.rb:188:in`process_action'
  actionpack (5.0.0) lib/action_controller/metal/rendering.rb:30:in `process_action'
  actionpack (5.0.0) lib/abstract_controller/callbacks.rb:20:in`block in process_action'
  activesupport (5.0.0) lib/active_support/callbacks.rb:126:in `call'
  activesupport (5.0.0) lib/active_support/callbacks.rb:506:in`block (2 levels) in compile'
  activesupport (5.0.0) lib/active_support/callbacks.rb:455:in `call'
  activesupport (5.0.0) lib/active_support/callbacks.rb:101:in`__run_callbacks__'
  activesupport (5.0.0) lib/active_support/callbacks.rb:750:in `_run_process_action_callbacks'
  activesupport (5.0.0) lib/active_support/callbacks.rb:90:in`run_callbacks'
  actionpack (5.0.0) lib/abstract_controller/callbacks.rb:19:in `process_action'
  actionpack (5.0.0) lib/action_controller/metal/rescue.rb:20:in`process_action'
  actionpack (5.0.0) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
  activesupport (5.0.0) lib/active_support/notifications.rb:164:in`block in instrument'
  activesupport (5.0.0) lib/active_support/notifications/instrumenter.rb:21:in `instrument'
  activesupport (5.0.0) lib/active_support/notifications.rb:164:in`instrument'
  actionpack (5.0.0) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
  actionpack (5.0.0) lib/action_controller/metal/params_wrapper.rb:248:in`process_action'
  activerecord (5.0.0) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  actionpack (5.0.0) lib/abstract_controller/base.rb:126:in`process'
  actionview (5.0.0) lib/action_view/rendering.rb:30:in `process'
  actionpack (5.0.0) lib/action_controller/metal.rb:190:in`dispatch'
  actionpack (5.0.0) lib/action_controller/metal.rb:262:in `dispatch'
  actionpack (5.0.0) lib/action_dispatch/routing/route_set.rb:50:in`dispatch'
  actionpack (5.0.0) lib/action_dispatch/routing/route_set.rb:32:in `serve'
  actionpack (5.0.0) lib/action_dispatch/journey/router.rb:39:in`block in serve'
  actionpack (5.0.0) lib/action_dispatch/journey/router.rb:26:in `serve'
  actionpack (5.0.0) lib/action_dispatch/routing/route_set.rb:725:in`call'
  warden (1.2.6) lib/warden/manager.rb:35:in `block in call'
  warden (1.2.6) lib/warden/manager.rb:34:in`call'
  rack (2.0.1) lib/rack/etag.rb:25:in `call'
  rack (2.0.1) lib/rack/conditional_get.rb:25:in`call'
  rack (2.0.1) lib/rack/head.rb:12:in `call'
  rack (2.0.1) lib/rack/session/abstract/id.rb:222:in`context'
  rack (2.0.1) lib/rack/session/abstract/id.rb:216:in `call'
  actionpack (5.0.0) lib/action_dispatch/middleware/cookies.rb:613:in`call'
  activerecord (5.0.0) lib/active_record/migration.rb:552:in `call'
  actionpack (5.0.0) lib/action_dispatch/middleware/callbacks.rb:38:in`block in call'
  activesupport (5.0.0) lib/active_support/callbacks.rb:97:in `__run_callbacks__'
  activesupport (5.0.0) lib/active_support/callbacks.rb:750:in`_run_call_callbacks'
  activesupport (5.0.0) lib/active_support/callbacks.rb:90:in `run_callbacks'
  actionpack (5.0.0) lib/action_dispatch/middleware/callbacks.rb:36:in`call'
  actionpack (5.0.0) lib/action_dispatch/middleware/executor.rb:12:in `call'
  actionpack (5.0.0) lib/action_dispatch/middleware/remote_ip.rb:79:in`call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:84:in `protected_app_call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:79:in`better_errors_call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:57:in `call'
  actionpack (5.0.0) lib/action_dispatch/middleware/debug_exceptions.rb:49:in`call'
  actionpack (5.0.0) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
  railties (5.0.0) lib/rails/rack/logger.rb:36:in`call_app'
  railties (5.0.0) lib/rails/rack/logger.rb:24:in `block in call'
  activesupport (5.0.0) lib/active_support/tagged_logging.rb:70:in`block in tagged'
  activesupport (5.0.0) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (5.0.0) lib/active_support/tagged_logging.rb:70:in`tagged'
  railties (5.0.0) lib/rails/rack/logger.rb:24:in `call'
  request_store (1.3.1) lib/request_store/middleware.rb:9:in`call'
  actionpack (5.0.0) lib/action_dispatch/middleware/request_id.rb:24:in `call'
  rack (2.0.1) lib/rack/method_override.rb:22:in`call'
  rack (2.0.1) lib/rack/runtime.rb:22:in `call'
  activesupport (5.0.0) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in`call'
  actionpack (5.0.0) lib/action_dispatch/middleware/executor.rb:12:in `call'
  actionpack (5.0.0) lib/action_dispatch/middleware/static.rb:136:in`call'
  rack (2.0.1) lib/rack/sendfile.rb:111:in `call'
  railties (5.0.0) lib/rails/engine.rb:522:in`call'
  puma (3.6.0) lib/puma/configuration.rb:225:in `call'
  puma (3.6.0) lib/puma/server.rb:578:in`handle_request'
  puma (3.6.0) lib/puma/server.rb:415:in `process_client'
  puma (3.6.0) lib/puma/server.rb:275:in`block in run'
  puma (3.6.0) lib/puma/thread_pool.rb:116:in `block in spawn_thread'
`

### PR DESCRIPTION
**Pull request by pudiva**
Looks like a similar change was done and undone several tiems in teh
past...

### CODE REVIEW

**Comment by mcritchlow** [comment]
👍 ran into this as well w/ Rails 5

**Comment by thiagogsr** [comment]
Why was it not merged? How do you are running it in production environment using `sass-rails`?

**Comment by OpenCoderX** [comment]
Is this still necessary? The gem works in my projects when I add select2 to the js and css asset manifest files.

**Comment by pudiva** [comment]
> Is this still necessary? The gem works in my projects when I add select2 to the js and css asset manifest files.

If you `rails new`, add the gem and it works, then it's not necessary anymore. The original author of the issue said it's been fixed already:

https://github.com/argerim/select2-rails/issues/164#issuecomment-403371056

I haven't tested, it's been 4 years now...

**Comment by ghost** [comment]
@ayghor I'll close this. Thanks!

**Pull request closed without merging**
