### PR TITLE
Switch to Select2 4.0.0 branch

### PR DESCRIPTION
**Pull request by frodrigo**
Switch to Select2 4.0.0 branch

### CODE REVIEW

**Comment by randallreedjr** [comment]
Select2 is now on 4.0.0-rc.2

**Comment by FabienChaynes** [comment]
Select2 is now on 4.0.0

**Comment by corroded** [comment]
Any idea when this will be merged? Thanks!

**Comment by kevin-brown** [comment]
This needs to be updated with the latest master before it can be automatically merged.

**Comment by frodrigo** [comment]
I rebase on master. But, please check, there was numerous conflicts

**Comment by mli-max** [comment]
You need look into https://github.com/fk/select2-bootstrap-theme It's theme for select2 4.0, currently in beta

**Comment by frodrigo** [comment]
Rewrite history to not delete select2-bootstrap.css and then update it.

**Comment by goravbhootra** [comment]
Any timeline when this will be merged?
Thanks.

**Comment by syndbg** [comment]
Bump. This should be merged. 4.0.0 is official for select2

**Comment by steijgeler** [comment]
Merge maybe?

**Comment by eljojo** [comment]
image

**Comment by richistron** [comment]
+1 merge please

**Comment by richistron** [comment]
LGTM!
[LGTM](http://lgtm.in/i/O3X6owBbq)

[:+1:](http://lgtm.in/u/O3X6owBbq) [:-1:](http://lgtm.in/r/O3X6owBbq)

**Comment by Bhaall** [comment]
LGTM

**Comment by nilbus** [comment]
This branch functions well in an app, but the `rake update-select2` task is broken. I have fixed this in #129.

**Comment by plentz** [comment]
his was already fixed, right?

**Comment by simi** [comment]
@plentz yes - https://github.com/argerim/select2-rails/releases/tag/v4.0.0

**Pull request closed without merging**
