### PR TITLE
Update to Select2 4.0.1 and select2-bootstrap.css to 0.1.0-beta.4

### PR DESCRIPTION
**Pull request by Eric-Guo**
Just purely update, tested at [cloud-mes](https://github.com/cloud-mes/cloud-mes/commit/3c5e4796cab15d660b5bbe80847717f55d15dcd0)

### CODE REVIEW

**Comment by simi** [comment]
I can see some differences in languages. @zeldalink0515 added more languages. Can you please do the same here?

**Comment by Eric-Guo** [comment]
My:

```ruby
"ar", "az", "bg", "ca", "cs", "da", "de", "en", "es", "et", "eu", "fa", "fi", "fr", "gl", "he", "hi", "hr", "hu",
"id", "is", "it", "ja", "ko", "lt", "lv", "mk", "ms", "nb", "nl", "pl", "pt-BR", "pt", "ro", "ru",
"sk", "sr", "sr-Cyrl", "sv", "th", "tr", "uk", "vi", "zh-CN", "zh-TW"
```

@zeldalink0515:
```ruby
"ar", "az", "bg", "ca", "cs", "da", "de", "en", "es", "et", "eu", "fa", "fi", "fr", "gl", "he", "hi", "hr", "hu",
"id", "is", "it", "ja", "ko", "lt", "lv", "mk", "ms", "nb", "nl", "pl", "pt", "pt-BR", "ro", "ru",
"sk", "sr", "sr-Cyrl", "sv", "th", "tr", "uk", "vi", "zh-CN", "zh-TW"
```

It's exactly same, I have change one additiona file `select2-bootstrap.css`, so there is 50 files in my PR and 49 files in his.

**Comment by simi** [comment]
Ahh sorry @Eric-Guo.

@zeldalink0515, @t0kieu, @AlexKovynev, @savmac please can you test and confirm everything is allright? I'm going to release new version if you can confirm.

**Comment by simi** [comment]
And thanks all for great work and pull requests!

**Pull request merged**
