### PR TITLE
select2 4.0.3 -> 4.0.6

### PR DESCRIPTION
**Pull request by ADikmarov**
Hi. The new version of Select2 (4.0.6) fixes most of the bugs in IE11. 
We use it on the project.
I would be very grateful for the upgrade version

### CODE REVIEW

**Comment by ashaninBenjamin** [comment]
👍

**Comment by p-salido** [comment]
Is this 4.0.6 final or RC?

**Comment by ADikmarov** [comment]
@p-salido RC version

**Comment by p-salido** [comment]
Then this needs to be appropriately indicated in the version numbers. What will happen when 4.0.6 final is released?

**Comment by mabdelfattah** [comment]
I made a separate fork with a separate gem that includes latest select2 versions and latest bootstrap theme version too. You can find it here if you are interested: https://rubygems.org/gems/select2-rails-latest

**Comment by OpenCoderX** [comment]
Version 4.0.6 is available: https://github.com/argerim/select2-rails/releases/tag/v4.0.6

**Pull request closed without merging**
