### PR TITLE
Update select2-bootstrap.css

### PR DESCRIPTION
**Pull request by newdark**
A group has done some of the work to help out with making this bootstrap like. There are a few more features as well as some other cool peaces in this css change. I would recommend using this in your gem. 

https://fk.github.io/select2-bootstrap-css/

### CODE REVIEW

**Comment by jordigg** [comment]
@argerim please accept this merge request to update the bootstrap styles :smile:

**Comment by griffithac** [comment]
@argerim I have added this same css (https://fk.github.io/select2-bootstrap-css/) to my project as well.  This is of course because select2-rails doesn't currently support Bootstrap 3.  If 85091b3 can't be merged as requested by @newdark suggests, why not just add a new css file called select2-bootstrap3.css?  This way support for Bootstrap 2 would still remain as is.  If you like, I a will add a pull request with the new file and update the readme.

**Comment by newdark** [comment]
I agree with @griffithac I have added the same css file to my application as well. In fact create a hole gem for my company on a private github repo just to fix this very bug. I would hope this would help please merge this request.

**Comment by newdark** [comment]
@argerim Please accept this merge request :+1:

**Pull request merged**
