### PR TITLE
Update select2 from 4.0.3 -> 4.0.13

### PR DESCRIPTION
**Pull request by pdobb**
See https://github.com/select2/select2/blob/develop/CHANGELOG.md#4013
for changes in select2 versions since 4.0.3.

I updated the code with `rake update-select2` and selected tag ~4.0.8~ 4.0.13. (Cool feature!)

### CODE REVIEW

**Comment by mattolson** [comment]
🙏

**Comment by remofritzsche** [comment]
Thanks for a merge 🙏

**Comment by TylerRick** [comment]
Please merge.

:bulb: Never mind. Switching to:
```haml
= stylesheet_link_tag 'https://cdn.jsdelivr.net/npm/select2@4.0.7/dist/css/select2.min.css'
= javascript_include_tag 'https://cdn.jsdelivr.net/npm/select2@4.0.3/dist/js/select2.full.min.js'
```
:smile: 

Sprocket asset gems seem like an unsustainable option that will always lag behind official releases...

**Comment by pdobb** [comment]
Now updated for select2 v4.0.8.

**Comment by cprodhomme** [comment]
@argerim

**Review by cprodhomme — APPROVED** [review]

**Comment by pdobb** [comment]
Looks like select2 is up to 4.0.13 now 🤷🏻‍♂️

**Comment by pdobb** [comment]
Added a commit to update to select2 v4.0.13 for all to benefit.

**Comment by ghost** [comment]
Version 4.0.13 available: https://github.com/argerim/select2-rails/releases/tag/v4.0.13

**Pull request closed without merging**
