### PR TITLE
update select2 to 4.0.4

### PR DESCRIPTION
**Pull request by Aralnoth**
Update select2 from 4.0.3 to 4.0.4

### CODE REVIEW

**Comment by trostli** [comment]
👍 please merge

**Comment by mabdelfattah** [comment]
I made a separate fork with a separate gem that includes latest select2 versions and latest bootstrap theme version too. You can find it here if you are interested: https://rubygems.org/gems/select2-rails-latest

**Comment by mattolson** [comment]
I need bug fixes from more recent versions of select2, particularly from 4.0.4. Any chance we can get this merged? Otherwise, I will need to start managing select2 on my own.

**Comment by Schwad** [comment]
Moving to `select2-rails-latest` or self managed

**Comment by vikramgupta1988** [comment]
@Schwad Ids it working `select2-rails-latest`? I'm getting error like 

`Sprockets::FileNotFound - couldn't find file 'select2' with type 'application/javascript'
Checked in these paths: 
  /Users/vikramgupta/.rvm/gems/ruby-2.4.1/gems/babel-source-5.8.35/lib
  /Users/vikramgupta/Unbxd/console/app/assets/fonts
  /Users/vikramgupta/Unbxd/console/app/assets/images
  /Users/vikramgupta/Unbxd/console/app/assets/javascripts
  /Users/vikramgupta/Unbxd/console/app/assets/stylesheets
  /Users/vikramgupta/Unbxd/console/vendor/assets/javascripts
  /Users/vikramgupta/Unbxd/console/vendor/assets/stylesheets
  /Users/vikramgupta/.rvm/gems/ruby-2.4.1/gems/remotipart-1.3.1/vendor/assets/javascripts
  /Users/vikramgupta/.rvm/gems/ruby-2.4.1/gems/delayed-web-0.4.3/app/assets/stylesheets
  /Users/vikramgupta/.rvm/gems/ruby-2.4.1/gems/delayed-web-0.4.3/vendor/assets/images`

**Comment by OpenCoderX** [comment]
4.0.4 released

**Pull request closed without merging**
